# Generated by Django 4.2 on 2023-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
