# Generated by Django 4.2 on 2023-04-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
