# Generated by Django 4.2 on 2023-04-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_no_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_views',
            new_name='no_of_views',
        ),
    ]
